import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { StoryService } from 'src/app/services/story.service';

@Component({
  selector: 'app-auto-generate-sprint',
  templateUrl: './auto-generate-sprint.component.html',
  styleUrls: ['./auto-generate-sprint.component.css']
})
export class AutoGenerateSprintComponent implements OnChanges{

  @Input() sprintPoint! :any
  autoGeneratedStories: any = [];
  defaultColor = "#ebebeb";


  constructor(
    private storyService : StoryService
  ){}

  ngOnChanges(): void {
      this.storyService.getStoriesBySprintPoint(this.sprintPoint).subscribe({
        next: (res) => {
          console.log("HAHGAHA", res), 
          this.autoGeneratedStories = res
      }
      })
  }

  

}
