import {
  Component,
  Input,
  OnChanges,
} from '@angular/core';
import { FormGroup } from '@angular/forms';
import { StoryService } from 'src/app/services/story.service';
import { ToastrService } from 'ngx-toastr';
@Component({
  selector: 'app-auto-generate-sprint',
  templateUrl: './auto-generate-sprint.component.html',
  styleUrls: ['./auto-generate-sprint.component.css'],
})
export class AutoGenerateSprintComponent implements OnChanges {
  @Input() sprintPoint!: any;
  @Input() deletedStories!: any;

  autoGeneratedStories: any = [];
  defaultColor = '#ebebeb';

  constructor(
    private storyService: StoryService,
    private toastr: ToastrService
  ) {}

  ngOnChanges(): void {
    this.storyService.getStoriesBySprintPoint(this.sprintPoint).subscribe({
      next: (res) => {
        this.autoGeneratedStories = res;
      },
      error: (err) => this.toastr.warning('Error', err),
    });
  }
}
